services:
  database:
    image: mysql
    volumes:
      - helth-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'health-monitor'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'app'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'h3417h-m0n170r'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Estafeta,13'
    expose:
      - 3306
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'

volumes:
  helth-mysql: